add make target for observability operator
RHCloudServices/kafka-monitoring-stuff pull request #105
Opened 2021-02-25 10:34 UTC by StevenTobin

## What
https://issues.redhat.com/browse/MGDSTRM-1433

## Why
The Makefile currently supports installing stand alone grafana and prometheus which does not reflect the actual stack in use.

## How
Adds a Makefile recipe for installing the observability operator with instructions for use.

2021-02-25 15:02 UTC, jeremyary requested changes

2021-02-25 15:02 UTC, jeremyary commented on README.md
> +* Click `install`
IMO, we should go ahead and create the `Namespace` (or Project, whichever) and the `Subscription` to automate this step as well.

2021-02-25 15:02 UTC, jeremyary commented on install/resources/observability-operator/catalogue-source.yaml
> +  namespace: kafka-observability
AFAICT, we should be creating this namespace/project programatically as well or all the following resource creations will fail.

2021-02-25 16:42 UTC, StevenTobin commented on install/Makefile
> +	@oc delete project $(OBSERVABILITY_NAMESPACE)
I've fixed that now, it deletes the cr and then the namespace.

2021-02-25 16:42 UTC, StevenTobin commented on README.md
> +|ACCESS_TOKEN | Github access token to pull observability resources |
Of course, I've added that info to the README now.

2021-02-25 16:43 UTC, StevenTobin commented on README.md
> +* Click `install`
Yep, added that.

2021-02-25 16:43 UTC, StevenTobin commented on install/resources/observability-operator/catalogue-source.yaml
> +  namespace: kafka-observability
Added the operatorgroup and subscription so it now automagically provisions the operator.

2021-02-25 19:25 UTC, jeremyary approved these changes
LGTM, thanks for the changes!

2021-02-25 19:45 UTC, tonyxrmdavidson commented
Ran the script from a mac. The sed command does not work when deploying locally from a mac. Does work when replaced with a gsed command.

2021-03-02 09:42 UTC, tonyxrmdavidson commented
/lgtm  observability operator successfully installed from mac with latest commit.

2021-03-02 09:43 UTC, merged