"SOP doc for kafka logging levels"
RHCloudServices/kafka-monitoring-stuff pull request #66
Opened 2020-11-26 11:39 UTC by ramu11

Document in form of SOP (standard operating procedure) steps to update initial log verbosity level identified in MGDSTRM-161  for strimzi, kafka and zookeeper components in cases 

## when SRE engineer requires more detailed information for root cause analysis  

##

2020-11-26 11:52 UTC, ramu11 commented
@StevenTobin  please review

2020-11-26 12:20 UTC, StevenTobin requested changes

2020-11-26 12:20 UTC, StevenTobin commented on sops/MGDSTRM-421.asciidoc
> +```
A code block should only contain a command you want an SRE to run with an optional example output from that command.

Any descriptive or instructional text about that command should come before or after the code block. It should be very obvious to an SRE what commands they should run.

2020-11-26 12:20 UTC, StevenTobin commented on sops/MGDSTRM-421.asciidoc
> +> OSD cluster with kube admin credentials is required. OC client configured with the login token
It's not necessary to have kubeadmin. You need a user with access to configmaps and kafka-clusters maybe? I'm not sure exactly but saying kubeadmin here is incorrect.

2020-11-26 12:20 UTC, StevenTobin commented on sops/MGDSTRM-421.asciidoc
> +   oc logs -f kafka-broker-pod/zookeeper-pod
We can assume an SRE knows how to access logs. If they specifically need to check something in the log you can call it out here, otherwise this is uneccesary.

2020-11-26 12:20 UTC, StevenTobin commented on sops/MGDSTRM-421.asciidoc
> += SOP document outlining steps to change log verbosity for kafka components
Title should just be the action

Changing log verbosity for kafka components

And the actual file name should be short, easy to search, make the purpose of the SOP obvious and be easy to access using the commandline something like
`changing_kafka_log_verbosity.asciidoc`

2020-11-26 12:20 UTC, StevenTobin commented on sops/MGDSTRM-421.asciidoc
> +   from log4j.properties
You should be speaking in actions. As an SRE I am looking at this SOP because I already know I can change the logging level.


Edit the `kafka.root.logger.level` `log4j.logger.kafka` and `log4j.logger.org.apache.kafka` properties in the `kafka-logging` configmap to the desired logging level
```
oc edit cm kafka-logging
```

You could move the example configmap in the Description section to here so an SRE can get an idea of the file layout.

2020-11-26 12:20 UTC, StevenTobin commented on sops/MGDSTRM-421.asciidoc
> +```
`check kafka broker logs are now coming in desired logging mode`

This should be the validate section. The purpose of the SOP is to change the logging level, you can't validate that by changing it back.

2020-11-26 12:43 UTC, StevenTobin commented on sops/MGDSTRM-421.asciidoc
> +   from log4j.properties
also when writing an oc command you should include `-n <NAMESPACE>` for safety

2020-11-26 13:58 UTC, ramu11 commented on sops/MGDSTRM-421.asciidoc
> +   oc logs -f kafka-broker-pod/zookeeper-pod
what to look in logs  based on what error it is throwing. I will provide some examples here

2020-11-26 13:58 UTC, ramu11 commented on sops/MGDSTRM-421.asciidoc
> += SOP document outlining steps to change log verbosity for kafka components
sure i will change the title

2020-11-26 13:59 UTC, ramu11 commented on sops/MGDSTRM-421.asciidoc
> +   from log4j.properties
ok

2020-11-26 14:54 UTC, ramu11 commented on sops/MGDSTRM-421.asciidoc
> +```
will remove code block

2020-11-26 14:56 UTC, ramu11 commented on sops/MGDSTRM-421.asciidoc
> +> OSD cluster with kube admin credentials is required. OC client configured with the login token
not sure sre can get to repective tenant cluster level to view logs to troubleshoot when issue pop up. Tenants kafka cluster logs and metrics will be on boraded to observatorium instance.
logs can be viewed from loki labels section by providing respective jobs. will add steps once this functionality is completely done. 

my be here observatorium will have service account for the tenant to get accessed from sre and tenents

2020-11-26 16:08 UTC, ramu11 commented on sops/MGDSTRM-421.asciidoc
> +```
done

2020-11-26 16:08 UTC, ramu11 commented on sops/MGDSTRM-421.asciidoc
> +   oc logs -f kafka-broker-pod/zookeeper-pod
done

2020-11-26 16:09 UTC, ramu11 commented on sops/MGDSTRM-421.asciidoc
> += SOP document outlining steps to change log verbosity for kafka components
done

2020-11-26 16:09 UTC, ramu11 commented on sops/MGDSTRM-421.asciidoc
> +```
done

2020-11-30 16:29 UTC, david-martin requested changes

2020-11-30 16:29 UTC, david-martin commented on sops/changing_kafka_log_verbosity.asciidoc
> +> As logs will be accessed from observatorium instance using loki from the dashborad. SRE should have access to the observatorium instance to view metrics and logs.
`SRE should have access to the observatorium instance`
Even though we know the target for the SOP is SRE, I think it's better not to assume.
e.g. `Access to the Kafka Observatorium tenant is required`

2020-11-30 16:29 UTC, david-martin commented on sops/changing_kafka_log_verbosity.asciidoc
> +   kafka-logging                 1      16m
From chatting with @ppatierno & @davidffrench , these configmaps are reconciled by the strimzi operator.
This means any changes to them will be reset.

For custom logging config, you can create a new configmap (as per https://strimzi.io/docs/operators/latest/using.html#external-logging_str),
but you also have to reference the configmap in the Kafka CR.

However, as the Kafka CR is reconciled by hive (from the service-api), any changes to the Kafka CR will also be reset thereby blowing away the configmap references.

One solution is to change the Kafka CR that the service-api reconciles to always reference custom configmaps (regardless of if they exist or not). 
This would allow the configmaps to be created/deleted as needed without fear of being reset. That puts an onus on the SOP executor to remove any custom logging config, which isn't ideal but at least it would enable what's needed for this SOP.

@ppatierno @davidffrench Does this make sense?
Any other ideas on how to solve this?

2020-11-30 17:05 UTC, davidffrench commented on sops/changing_kafka_log_verbosity.asciidoc
> +   kafka-logging                 1      16m
This will become easier once we move to using an agent operator since it would be the agent creating these resources and it is up to us to decide if the agent should reconcile the ConfigMap and how.

2020-11-30 21:19 UTC, ppatierno commented on sops/changing_kafka_log_verbosity.asciidoc
> +   kafka-logging                 1      16m
> One solution is to change the Kafka CR that the service-api reconciles to always reference custom configmaps (regardless of if they exist or not).

Not sure it's going to work. If you are referencing an external configmap for logging in your Kafka CR, it has to exist otherwise the cluster operator fails to reconcile.

2020-12-01 06:11 UTC, ramu11 commented on sops/changing_kafka_log_verbosity.asciidoc
> +   kafka-logging                 1      16m
@david-martin @ppatierno @davidffrench  Thanks for the review comments. The logging  configuration provided as an external config map (https://strimzi.io/docs/operators/latest/using.html#external-logging_str)

as hive is resetting config map changes. shall I create jira for managed-kafka to not reset the configmap? please suggest how to address this requirement?

2020-12-02 07:29 UTC, ramu11 commented on sops/changing_kafka_log_verbosity.asciidoc
> +   kafka-logging                 1      16m
![mk-cm](https://user-images.githubusercontent.com/16187022/100842021-3561a180-349e-11eb-9678-a6d8ba782433.png)

2020-12-02 07:30 UTC, ramu11 commented on sops/changing_kafka_log_verbosity.asciidoc
> +   kafka-logging                 1      16m
@david-martin  config maps are not getting deleted by strimzi opertaor

2020-12-02 11:04 UTC, david-martin approved these changes

2020-12-02 11:05 UTC, merged