added install/global/monitoring target
RHCloudServices/kafka-monitoring-stuff pull request #7
Opened 2020-09-21 13:54 UTC by jhellar

https://issues.redhat.com/browse/MGDSTRM-166

2020-09-21 14:11 UTC, damienomurchu commented on install/Makefile
> +	@ cp $(RESOURCE_FILES_DIR)/grafana/operatorgroup.yaml $(BUILD_DIR)/grafana/
Should we fetch the resources from operatorhub, ie `wget https://operatorhub.io/install/grafana-operator.yaml`

2020-09-21 14:12 UTC, damienomurchu commented on install/Makefile
> +	@ oc apply -f $(BUILD_DIR)/grafana/grafana.yaml
Perhaps remove the build files as the last step?

2020-09-21 14:13 UTC, damienomurchu commented
Looks good, left some small comments

2020-09-21 14:35 UTC, david-martin commented on install/Makefile
> +	@ cp $(RESOURCE_FILES_DIR)/grafana/operatorgroup.yaml $(BUILD_DIR)/grafana/
I'd prefer to check them in here for a couple reasons:
- avoid downtime issues with operatorhub
- allow easier tweaking of them in the short term

2020-09-21 14:37 UTC, david-martin commented on install/Makefile
> +	@ sed -i 's/<PER_CLUSTER_MONITORING_NAMESPACE>/$(PER_CLUSTER_MONITORING_NAMESPACE)/' $(BUILD_DIR)/grafana/*.yaml
Grafana should be installed into a non services specific namespace
e.g. `managed-services-monitoring`(nothing kafka specific)

2020-09-21 14:39 UTC, david-martin commented on install/Makefile
>  GLOBAL_MONITORING_NAMESPACE ?= kafka-monitoring-global
These vars are a little confusing.

There would be 2 namespaces where monitoring stuff goes.

- managed-services-monitoring (1 per OSD cluster, contains grafana (& prometheus in the short term))
- the strimzi operator namespace (Put strimzi/kafka specific resources)

2020-09-21 15:32 UTC, david-martin approved these changes

2020-09-21 15:33 UTC, david-martin requested changes
On hold pending #5

2020-09-21 16:01 UTC, jhellar commented on install/Makefile
> +	@ oc apply -f $(BUILD_DIR)/grafana/grafana.yaml
Makes sense, moved

2020-09-21 16:02 UTC, jhellar commented on install/Makefile
> +	@ sed -i 's/<PER_CLUSTER_MONITORING_NAMESPACE>/$(PER_CLUSTER_MONITORING_NAMESPACE)/' $(BUILD_DIR)/grafana/*.yaml
This is renamed now

2020-09-21 16:02 UTC, jhellar commented on install/Makefile
>  GLOBAL_MONITORING_NAMESPACE ?= kafka-monitoring-global
This should be renamed now as well

2020-09-22 09:11 UTC, pb82 commented
@jhellar #5 is merged now, can we also get this merged?

2020-09-22 09:27 UTC, damienomurchu approved these changes

2020-09-22 09:28 UTC, damienomurchu commented
@david-martin anything on your end holding back this from being merged now? All PR feedback looks to have been addressed

2020-09-22 09:32 UTC, david-martin commented
👀

2020-09-22 10:01 UTC, pb82 commented on install/Makefile
>  install/global/monitoring:
should this be `install/cluster/monitoring`

2020-09-22 10:19 UTC, pb82 commented on install/Makefile
> +	@ oc new-project $(PER_CLUSTER_MONITORING_NAMESPACE)
This fails on second run when the namespace already exists. You can use this to ignore the error:

`@ oc new-project $(PER_CLUSTER_MONITORING_NAMESPACE) | true`

2020-09-22 10:46 UTC, pb82 approved these changes
Verified locally

2020-09-22 10:47 UTC, merged