Added SOP for restarting master nodes
RHCloudServices/kafka-monitoring-stuff pull request #81
Opened 2021-01-12 21:38 UTC by robshelly

## What
SOP for restating master node instances in AWS

## Why
This SOP is needed when AWS retires EC2 instances which contain master nodes

## How
SOP added to sops directory

2021-01-13 09:20 UTC, StevenTobin commented
Looks like you're missing the commits, this is just the template

2021-01-13 10:10 UTC, StevenTobin requested changes

2021-01-13 10:10 UTC, StevenTobin commented on sops/restart-master-nodes.asciidoc
> +. Login to AWS Console. See AWS.
Is there supposed to be a link or something here?

2021-01-13 10:10 UTC, StevenTobin commented on sops/restart-master-nodes.asciidoc
> +. Verify the instanace is in an up and running state
Typo

2021-01-18 11:41 UTC, david-martin approved these changes
These steps look reasonable.
@StevenTobin Are you happy with your requested changes have all been addressed?

2021-01-18 12:00 UTC, StevenTobin approved these changes

2021-01-18 12:09 UTC, merged