Sop for updating the observability operator image
RHCloudServices/kafka-monitoring-stuff pull request #91
Opened 2021-02-08 10:34 UTC by obrienrobert

## What
[MGDSTRM-1455](https://issues.redhat.com/browse/MGDSTRM-1455)

## Why
The process of rolling a new Observability Operator image to staging is very much a manual process for now and isn't documented. This SOP provides the steps to deploy and validate a new image version.

## How

2021-02-08 10:51 UTC, david-martin requested changes

2021-02-08 10:51 UTC, david-martin commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +  - promtaila-config
```suggestion
  - promtail-config
```

2021-02-08 10:51 UTC, david-martin commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +oc rollout restart deployment -n <namespace> && oc rollout restart statefulset -n <namespace>
```suggestion
oc rollout restart deployment -n managed-application-services-observability && oc rollout restart statefulset -n managed-application-services-observability
```

2021-02-08 10:51 UTC, david-martin commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +oc get pods -n <namespace>
```suggestion
oc get pods -n managed-application-services-observability
```

2021-02-08 10:51 UTC, david-martin commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +quay.io/integreatly/observability-operator   latest
@pb82 Not a blocker to merge this now, but do we have a jira for any changes to the process for building/tagging/testing images?
The image to use should already be built, tagged and tested before being rolled out.

2021-02-08 10:51 UTC, david-martin commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +make docker-build
@obrienrobert Does this produce the same artifact regardless of which machine it was run on?
For example, is the build containerised, or would things like dev environment (golang version) potentially result in a different image?

2021-02-08 10:51 UTC, david-martin commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +1. The target OSD staging cluster exists. The `ID` of the target cluster can be obtained from the output of the following command:
@davidffrench @JameelB  
How would you recommend identifying a data plane cluster when using `ocm`?
Based on the name, or are there labels or other metadata we can filter on?

2021-02-08 10:51 UTC, david-martin commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +2. Some resources do not get updated when a new image is deployed. If the new image contains changes to any of the following resources, the resource must be updated manually in the cluster:
@obrienrobert I'd like to see a jira linked here that captures the work to automate this.

2021-02-08 10:56 UTC, obrienrobert commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +  - promtaila-config
@david-martin `promtaila-config` is the name of the config-map in `v1`. Possibly a typo in the code itself?

2021-02-08 10:58 UTC, davidffrench commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +1. The target OSD staging cluster exists. The `ID` of the target cluster can be obtained from the output of the following command:
That is a good question @david-martin . We don't currently add a label to the cluster that I am aware of but this is likely the best solution.

2021-02-08 11:15 UTC, davidffrench commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +1. The target OSD staging cluster exists. The `ID` of the target cluster can be obtained from the output of the following command:
Create a JIRA for this - https://issues.redhat.com/browse/MGDSTRM-1535. It will be a good first issue for Dimitri to pick up

2021-02-08 11:16 UTC, JameelB commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +1. The target OSD staging cluster exists. The `ID` of the target cluster can be obtained from the output of the following command:
I agree, I think adding a label to the cluster would be the best. For now you can identify the cluster if they are prefixed with `ms-`. If you can check the user who created it, it should also be created by our service account.

2021-02-08 11:23 UTC, david-martin commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +1. The target OSD staging cluster exists. The `ID` of the target cluster can be obtained from the output of the following command:
That sounds useful to add here @obrienrobert .

@JameelB I noticed other clusters with an `ms-` prefix show up now and again though. Would they have been development clusters (someone running the service-api locally) ?
Is the combo of both the prefix and the service account who created it sufficient then?
Also, how to check who created them?

2021-02-08 11:48 UTC, JameelB commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +1. The target OSD staging cluster exists. The `ID` of the target cluster can be obtained from the output of the following command:
@david-martin They're development clusters created by the team running the service-api locally. 

You can check who created them via accounts_mgmt. If you get the cluster object from ocm, there should be a field called `subscription` with a subscription link from accounts_mgmt. The object returned from that should have a `creator` field with a link to the account details. Im not sure what user you need to get the details from that link though but it should have the account id in the link.

2021-02-08 11:53 UTC, obrienrobert commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +2. Some resources do not get updated when a new image is deployed. If the new image contains changes to any of the following resources, the resource must be updated manually in the cluster:
[MGDSTRM-1539](https://issues.redhat.com/browse/MGDSTRM-1539)

2021-02-08 11:58 UTC, david-martin commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +2. Some resources do not get updated when a new image is deployed. If the new image contains changes to any of the following resources, the resource must be updated manually in the cluster:
Thanks @obrienrobert 
You can add it to the doc so whenever someone is following the SOP, they can check if this step is still needed.

Also, I wonder if there's something like this already on one of the backlogs?
Maybe https://issues.redhat.com/browse/MGDSTRM-882 ?

2021-02-09 09:47 UTC, obrienrobert commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +make docker-build
@david-martin the make target uses a Docker file which uses [GO v1.13](https://github.com/bf2fc6cc711aee1a0c2a/observability-operator/blob/v1/Dockerfile#L2) to build the image so I don't think the user's local GO version will produce a different image.

2021-02-09 11:54 UTC, obrienrobert commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +1. The target OSD staging cluster exists. The `ID` of the target cluster can be obtained from the output of the following command:
@JameelB If I retrieve the `creator` field from the current cluster in staging I get the following:
```json
  "creator": {
    "id": "<account_id>",
    "kind": "Account",
    "href": "/api/accounts_mgmt/v1/accounts/<account_id>"
  },
```
Is it enough to use the `<account_id>` value to identify the staging cluster do you think?

2021-02-09 14:09 UTC, JameelB commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +1. The target OSD staging cluster exists. The `ID` of the target cluster can be obtained from the output of the following command:
Yes the `<account_id>` should be enough, it should be unique to each account.

2021-02-09 14:27 UTC, obrienrobert commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +2. Some resources do not get updated when a new image is deployed. If the new image contains changes to any of the following resources, the resource must be updated manually in the cluster:
@david-martin I've added a link to the JIRA. I'm not really sure about the JIRA you linked or how it ties in, to be honest, as I'm not familiar with syncsets.

2021-02-09 14:58 UTC, jeremyary commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +quay.io/integreatly/observability-operator   latest
For automation, I believe the closest we have would be a generic support for CI/CD in [MGDSTRM-](https://issues.redhat.com/browse/MGDSTRM-1049). For manual short-term process, no, we've only briefly discussed tagging strategy and no related issue.

2021-02-09 15:05 UTC, jeremyary commented on sops/updating_observability_operator_image_in_stage.asciidoc
> +  - promtaila-config
We really would benefit from getting staging out of v1... Promtail config is addressed by a [recent PR](https://github.com/bf2fc6cc711aee1a0c2a/observability-operator/pull/23) and will affect its inclusion here. The alertmanager secret is now managed by the operator as well. I honestly haven't noticed the proxies, though, so not sure on those.

2021-02-12 09:49 UTC, merged